version: '3.8'

services:
  app:
    build: ./node
    container_name: node-app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm start"
    networks:
      - fullcycle-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullcycle-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fullcycle-network

volumes:
  mysql-data:

networks:
  fullcycle-network:
    driver: bridge
